// <auto-generated />
using System;
using MAgicVilla_VillaAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MAgicVilla_VillaAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MAgicVilla_VillaAPI.Models.Villa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Amenity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Occupancy")
                        .HasColumnType("int");

                    b.Property<double>("Rate")
                        .HasColumnType("float");

                    b.Property<int>("Sqft")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Villas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amenity = "",
                            CreatedDate = new DateTime(2023, 2, 28, 16, 45, 25, 736, DateTimeKind.Local).AddTicks(9387),
                            Details = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
                            ImageUrl = "https://img.freepik.com/free-photo/house-isolated-field_1303-23773.jpg?w=1380&t=st=1677591271~exp=1677591871~hmac=180ca56a4f333bf1655b7ddd68ef19d3577034bfccb003020cd4a6744ca5e7cc",
                            Name = "Great Villa",
                            Occupancy = 5,
                            Rate = 200.0,
                            Sqft = 550,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            Amenity = "",
                            CreatedDate = new DateTime(2023, 2, 28, 16, 45, 25, 736, DateTimeKind.Local).AddTicks(9405),
                            Details = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
                            ImageUrl = "https://img.freepik.com/free-photo/house-isolated-field_1303-23773.jpg?w=1380&t=st=1677591271~exp=1677591871~hmac=180ca56a4f333bf1655b7ddd68ef19d3577034bfccb003020cd4a6744ca5e7cc",
                            Name = "Best Villa",
                            Occupancy = 5,
                            Rate = 200.0,
                            Sqft = 750,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            Amenity = "",
                            CreatedDate = new DateTime(2023, 2, 28, 16, 45, 25, 736, DateTimeKind.Local).AddTicks(9406),
                            Details = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
                            ImageUrl = "https://img.freepik.com/free-photo/house-isolated-field_1303-23773.jpg?w=1380&t=st=1677591271~exp=1677591871~hmac=180ca56a4f333bf1655b7ddd68ef19d3577034bfccb003020cd4a6744ca5e7cc",
                            Name = "Shark Villa",
                            Occupancy = 5,
                            Rate = 200.0,
                            Sqft = 650,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            Amenity = "",
                            CreatedDate = new DateTime(2023, 2, 28, 16, 45, 25, 736, DateTimeKind.Local).AddTicks(9408),
                            Details = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
                            ImageUrl = "https://img.freepik.com/free-photo/house-isolated-field_1303-23773.jpg?w=1380&t=st=1677591271~exp=1677591871~hmac=180ca56a4f333bf1655b7ddd68ef19d3577034bfccb003020cd4a6744ca5e7cc",
                            Name = "Best of The best Villa",
                            Occupancy = 5,
                            Rate = 200.0,
                            Sqft = 850,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            Amenity = "",
                            CreatedDate = new DateTime(2023, 2, 28, 16, 45, 25, 736, DateTimeKind.Local).AddTicks(9409),
                            Details = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
                            ImageUrl = "https://img.freepik.com/free-photo/house-isolated-field_1303-23773.jpg?w=1380&t=st=1677591271~exp=1677591871~hmac=180ca56a4f333bf1655b7ddd68ef19d3577034bfccb003020cd4a6744ca5e7cc",
                            Name = "Small small Villa",
                            Occupancy = 5,
                            Rate = 200.0,
                            Sqft = 130,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 6,
                            Amenity = "",
                            CreatedDate = new DateTime(2023, 2, 28, 16, 45, 25, 736, DateTimeKind.Local).AddTicks(9411),
                            Details = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
                            ImageUrl = "https://img.freepik.com/free-photo/house-isolated-field_1303-23773.jpg?w=1380&t=st=1677591271~exp=1677591871~hmac=180ca56a4f333bf1655b7ddd68ef19d3577034bfccb003020cd4a6744ca5e7cc",
                            Name = "Vintage Villa",
                            Occupancy = 5,
                            Rate = 200.0,
                            Sqft = 450,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 7,
                            Amenity = "",
                            CreatedDate = new DateTime(2023, 2, 28, 16, 45, 25, 736, DateTimeKind.Local).AddTicks(9412),
                            Details = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
                            ImageUrl = "https://img.freepik.com/free-photo/house-isolated-field_1303-23773.jpg?w=1380&t=st=1677591271~exp=1677591871~hmac=180ca56a4f333bf1655b7ddd68ef19d3577034bfccb003020cd4a6744ca5e7cc",
                            Name = "Cool Villa",
                            Occupancy = 5,
                            Rate = 200.0,
                            Sqft = 250,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 8,
                            Amenity = "",
                            CreatedDate = new DateTime(2023, 2, 28, 16, 45, 25, 736, DateTimeKind.Local).AddTicks(9413),
                            Details = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
                            ImageUrl = "https://img.freepik.com/free-photo/house-isolated-field_1303-23773.jpg?w=1380&t=st=1677591271~exp=1677591871~hmac=180ca56a4f333bf1655b7ddd68ef19d3577034bfccb003020cd4a6744ca5e7cc",
                            Name = "Very small Villa",
                            Occupancy = 5,
                            Rate = 200.0,
                            Sqft = 150,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 9,
                            Amenity = "",
                            CreatedDate = new DateTime(2023, 2, 28, 16, 45, 25, 736, DateTimeKind.Local).AddTicks(9415),
                            Details = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
                            ImageUrl = "https://img.freepik.com/free-photo/house-isolated-field_1303-23773.jpg?w=1380&t=st=1677591271~exp=1677591871~hmac=180ca56a4f333bf1655b7ddd68ef19d3577034bfccb003020cd4a6744ca5e7cc",
                            Name = "Big Villa",
                            Occupancy = 5,
                            Rate = 200.0,
                            Sqft = 520,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 10,
                            Amenity = "",
                            CreatedDate = new DateTime(2023, 2, 28, 16, 45, 25, 736, DateTimeKind.Local).AddTicks(9416),
                            Details = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
                            ImageUrl = "https://img.freepik.com/free-photo/house-isolated-field_1303-23773.jpg?w=1380&t=st=1677591271~exp=1677591871~hmac=180ca56a4f333bf1655b7ddd68ef19d3577034bfccb003020cd4a6744ca5e7cc",
                            Name = "Very big Villa",
                            Occupancy = 7,
                            Rate = 200.0,
                            Sqft = 510,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
